name: Auto Deploy 
on: 
  push: 
    branches:
       - main
jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
            node-version: 16 # 指定node版本

      - name: Build
        run: |
          npm install 
          npm run build 
      - name: Deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: wuxin0011/vue-page
          TARGET_BRANCH: gh-pages
          BUILD_DIR: docs/.vuepress/dist/

 