name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: wuxin0011/vue-page@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: docs/.vuepress/dist/ # The folder, the action should deploy.
        BUILD_SCRIPT: npm install && npm run build # The build script the action should run prior to deploying.