name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: vuepress-deploy
      uses: wuxin0011/vue-page@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: wuxin0011/vue-page
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm install && npm run build
        BUILD_DIR: docs/.vuepress/dist/
